[package]
name = "example"
version = "0.1.0"
authors = ["Hirokazu MINAMI <hrkzmnm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3prover = { path = "../z3prover" }
make_ast = { path = "../make_ast" }